FROM --platform=linux/arm64/v8 python:3.12-slim

WORKDIR /app
# Copy app source
COPY . ./

# Install system dependencies for psycopg2
RUN apt-get update && apt-get install -y gcc libpq-dev lsof && rm -rf /var/lib/apt/lists/*

# Copy requirements
COPY requirements/app.txt ./

# Install Python dependencies
RUN pip install --no-cache-dir -r ./app.txt
